/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Item = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'owner' : IDL.Principal,
  'isShared' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createItem' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteItem' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getItem' : IDL.Func([IDL.Text], [IDL.Opt(Item)], ['query']),
  'getSharedItem' : IDL.Func([IDL.Text], [IDL.Opt(Item)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listUserItems' : IDL.Func([IDL.Principal], [IDL.Vec(Item)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'shareItem' : IDL.Func([IDL.Text], [], []),
  'unshareItem' : IDL.Func([IDL.Text], [], []),
  'updateItem' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Item = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'owner' : IDL.Principal,
    'isShared' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createItem' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteItem' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getItem' : IDL.Func([IDL.Text], [IDL.Opt(Item)], ['query']),
    'getSharedItem' : IDL.Func([IDL.Text], [IDL.Opt(Item)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listUserItems' : IDL.Func([IDL.Principal], [IDL.Vec(Item)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'shareItem' : IDL.Func([IDL.Text], [], []),
    'unshareItem' : IDL.Func([IDL.Text], [], []),
    'updateItem' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };